apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enhanced-devops-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=crmasraf001.azurecr.io/enhanced-devops
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-patko
    argocd-image-updater.argoproj.io/force-update: "true"
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:master-.*
spec:
  project: default
  source:
    repoURL: https://github.com/xokacar/clean-devops
    path: ./cleanchart
    targetRevision: HEAD
    helm:
      valueFiles:
        - ./cleanchart/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - Force=true
      - Validate=false
      - CreateNamespace=true
      - PruneLast=true
