apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enhanced-devops-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: app=crmasraf001.azurecr.io/enhanced-devops
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-patko
    argocd-image-updater.argoproj.io/core.allow-tags: regexp:^dev-[a-zA-Z0-9]*$
    argocd-image-updater.argoproj.io/force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/xokacar/clean-devops
    path: ./cleanchart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - Force=true
      - Validate=false
      - CreateNamespace=true
      - PruneLast=true
