apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: enhanced-devops-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: enhanced-devops=crmasraf001.azurecr.io/enhanced-devops:latest
    argocd-image-updater.argoproj.io/enhanced-devops.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-patko
    argocd-image-updater.argoproj.io/enhanced-devops.pull-secret: pullsecret:argocd/acr-secret
spec: 
  project: default
  source: 
    repoURL: https://github.com/xokacar/imup-middle
    path: ./cleanchart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
    - Force=true
    - Validate=false
    - CreateNamespace=true
    - PruneLast=true