apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater-sa-role
  namespace: argocd
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater-sa-role-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: argocd-image-updater-sa
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-image-updater-sa-role
  apiGroup: rbac.authorization.k8s.io
