replicaCount: 1

config:
  registries:
  - name: clean-devops
    prefix: crmasraf001.azurecr.io
    api_url: https://crmasraf001.azurecr.io
    credentials: argocd/acr-secret
    default: yes
    forceString: false
  cm:
    accounts.image-updater: apiKey


image:
  repository: crmasraf001.azurecr.io/enhanced-devops
  pullPolicy: Always
  tag: latest



imagePullSecrets:
  - name: acr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: clean-svcaccount


podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3002


ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
